/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package localstack.issue;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.DynamodbEvent;

public class Handler implements RequestHandler<DynamodbEvent, String> {
    @Override
    public String handleRequest(DynamodbEvent dynamodbEvent, final Context context) {
        LambdaLogger logger = context.getLogger();
        logger.log("Event: " + dynamodbEvent);
        logger.log("Yay issue is fixed!");
        return "Thank you";
    }
}